# Sample Server Configuration File for Epic-Miner
#
# Epic-Miner will look for this file in these places: in the following
# order:
#
# -The working directory
# -The directory in which the executable resides

#########################################
### LOGGING CONFIGURATION             ###
#########################################

[logging]

# Whether to log to stdout
log_to_stdout = true

# Log level for stdout: Critical, Error, Warning, Info, Debug, Trace
stdout_log_level = "Info"

# Whether to log to a file
log_to_file = true

# Log level for file: Critical, Error, Warning, Info, Debug, Trace
file_log_level = "Debug"

# Log file path
log_file_path = "./epic-miner.log"

# Whether to append to the log file (true), or replace it on every run (false)
log_file_append = true

#########################################
### MINING CLIENT CONFIGURATION       ###
#########################################

[mining]

# Cuckoo, RandomX, ProgPow
algorithm = "RandomX"

# whether to run the tui
run_tui = false

# listening epic stratum server url
stratum_server_addr = "us.epicmine.io:3333"

# login for the stratum server (if required)
#stratum_server_login = "ssl://xavixalkaf.tescpuz"

# password for the stratum server (if required)
stratum_server_password = "m=pool"

# whether tls is enabled for the stratum server
stratum_server_tls_enabled = true

#The directory in which mining plugins are installed
#if not specified, epic miner will look in the directory /deps relative
#to the executable

#miner_plugin_dir = "target/debug/plugins"

[mining.randomx_config]
threads = 3
jit = true
large_pages = false
hard_aes = false


